algorithms-and-glossary-web-app-master/PartB/Glossary/Controllers/GlossaryController.cs
using System.Net;
using System.Web.Mvc;
using EntityFrameworkRepository;
using GlossaryService;

namespace Glossary.Controllers
{
    public class GlossaryController : Controller
    {
        private ICustomGlossaryService _glossaryService;

        public GlossaryController()
        {
            // Todo - Replace with DI
            _glossaryService = new CustomGlossaryService(new GlossaryDbContext());
        }

        // GET: Glossaries
        public ActionResult Index()
        {
            return View(_glossaryService.GetAll());
        }

        // GET: Glossaries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Glossaries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Term,Definition")] EntityFrameworkRepository.Models.Glossary glossary)
        {
            if (ModelState.IsValid)
            {
                _glossaryService.Add(glossary);
                return RedirectToAction("Index");
            }

            return View(glossary);
        }

        // GET: Glossaries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var glossary = _glossaryService.Get(id.Value);
            if (glossary == null)
            {
                return HttpNotFound();
            }

            return View(glossary);
        }

        // POST: Glossaries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Term,Definition")] EntityFrameworkRepository.Models.Glossary glossary)
        {
            if (ModelState.IsValid)
            {
                _glossaryService.Update(glossary);
                return RedirectToAction("Index");
            }
            return View(glossary);
        }

        // GET: Glossaries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var glossary = _glossaryService.Get(id.Value);
            if (glossary == null)
            {
                return HttpNotFound();
            }

            return View(glossary);
        }

        // POST: Glossaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _glossaryService.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

algorithms-and-glossary-web-app-master/PartB/Glossary/Views/Glossary/Create.cshtml
@model EntityFrameworkRepository.Models.Glossary

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Glossary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Term, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Term, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Term, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Definition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Definition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Definition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

algorithms-and-glossary-web-app-master/PartB/Glossary/Views/Glossary/Delete.cshtml
@model EntityFrameworkRepository.Models.Glossary

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Glossary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Definition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Definition)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

algorithms-and-glossary-web-app-master/PartB/Glossary/Views/Glossary/Edit.cshtml
@model EntityFrameworkRepository.Models.Glossary

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Glossary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Term, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Term, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Term, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Definition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Definition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Definition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

algorithms-and-glossary-web-app-master/PartB/Glossary/Views/Glossary/Index.cshtml
@model IEnumerable<EntityFrameworkRepository.Models.Glossary>

@{
    ViewBag.Title = "Glossary List";
}

<h2>Glossary List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Term)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Definition)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Term, "Edit", new { id=item.ID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Definition)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

algorithms-and-glossary-web-app-master/PartB/Glossary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Glossary Manager", "Index", "Glossary", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create", "Create", "Glossary")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>